spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javacode2018?characterEncoding=UTF-8
    username: root
    password: 123456

server:
  port: 8199  # 默认端口



